Fixed-DatabaseConnection
Health-Informatics-UoN/lettuce pull request #30
Opened 2024-08-14 14:50 UTC by Karthi-DStech

Hi James, 

I've removed the executing logic of closing the database connection from OMOP_match.py to text_input.py. 

This is because, Lettuce treats the words individually and yields the results. I've tried mulitple times and techniques to solve the issue. 

Then I though of implementig this solution and worked well (as it was pretty straight forward and gives a solution). 

I've also tested the code and it works as expected. Kindly review the code and do the neetful. 

Thanks and regards,
Karthik

2024-08-27 12:28 UTC, kuraisle requested changes
This is an interesting solution. The issue I have with it is that the OMOPMatcher singleton is called from the UI, so is created client-side. This restricts deployment: if we run a LLettuce server, and have people open up the UI and call our API, this function won't work unless they have the authentication details for the OMOP server, which is not a behaviour we want

2024-08-27 18:57 UTC, Karthi-DStech commented
> This is an interesting solution. The issue I have with it is that the OMOPMatcher singleton is called from the UI, so is created client-side. This restricts deployment: if we run a LLettuce server, and have people open up the UI and call our API, this function won't work unless they have the authentication details for the OMOP server, which is not a behaviour we want

Thanks for your feedback. Actually, I tried not to modify the base logic as much as I could and If we want to implement the logic in OMOP matcher and app.py, we have to remove the yield and modify some logic. I'll start working on it and let you know the progress.

2024-08-30 10:53 UTC, kuraisle commented
Can't you just pass a list to OMOP_match.run? OMOPMatcher.calculate_best_matches takes a list

2024-09-02 11:32 UTC, Karthi-DStech commented
> Can't you just pass a list to OMOP_match.run? OMOPMatcher.calculate_best_matches takes a list

I've done the implementation in another pull request James. This was before fixing the multiple query commit.

2024-09-10 11:09 UTC, Karthi-DStech commented
Hi James, 

I've made changes to the database connection and it works well. I've moved the logic to `app.py` and tested the code. Kindly review it and do the needful. 

Thanks and regards,
Karthik

2024-09-11 08:18 UTC, kuraisle commented on Carrot-Assistant/app.py
> +    GPT_3_5_TURBO = ("gpt-3.5-turbo-0125",)
These shouldn't be wrapped in tuples

2024-09-12 16:15 UTC, closed without merging