Updated Commit
Health-Informatics-UoN/lettuce pull request #6
Opened 2024-07-26 09:03 UTC by Karthi-DStech

Hello Guys,

I've found the problem which causes error when installing the requirements of Carrot-Assistant. When we attempt to installing OpenSSL using pip, it throws an error. Also they were some other problems in conda level environment and the problem was in the Operating System level. 
 
So I created a script called (config.py) which will look for the type of OS and install all the package and dependencies and I've tested it in my local machine. The scripts are ready to install in other local machines. 

We need to make changes in the readme for lettuce repo. When Lettuce repo was cloned to the system, the user should run the following commands below:

-> chmod +x install_requirements.sh 

(This command will give permission to install the OpenSSH in the system. Since OpenSSH works in the OS level, the user needs to give permission for installing it). 

-> ./install_requirements.sh 

(This command will install all the packages and dependencies listed in "requirements.txt" and also checks whether OpenSSH is installed in the local computer. If OpenSSH is not available, the scripts will be installed and if OpenSSH version is not updated to the latest version, the scripts will update itself.).

Let me know for any changes and kindly do the needful.
Thanks and regards,
Karthik

2024-07-26 11:27 UTC, kuraisle requested changes
config.py should be removed, and install_requirements.sh should be edited so we don't mess with the OS level packages

2024-07-26 11:27 UTC, kuraisle commented on Carrot-Assistant/config.py
As I said the other day, I don't think we should do this. OpenSS**L** is an important part of security over networks and we shouldn't be messing with users' OS security. In any case, this installs OpenSS**H**, which we should also not touch

2024-07-26 11:27 UTC, kuraisle commented on install_requirements.sh
As with the config.py, we shouldn't mess with users' security

2024-08-02 09:34 UTC, Karthi-DStech commented on Carrot-Assistant/config.py
Ok James, I'll remove it.

2024-08-02 10:26 UTC, kuraisle approved these changes

2024-08-02 10:26 UTC, merged